
services:
  questdb:
    image: questdb/questdb:9.2.3
    container_name: questdb
    ports:
      - "9000:9000"  # Web Console
      - "8812:8812"  # PostgreSQL wire protocol
      - "9009:9009"  # Influx / HTTP API
    volumes:
      - questdb-data:/var/lib/questdb
volumes:
  questdb-data:
